### ISSUE TITLE
https://btranslator.org/ be able to get to the vocabularies

### ISSUE THREAD

**Issue by h4ck3rm1k3** [B-Translator/btr_server#25]
when you land on the site https://btranslator.org/ it would be nice to be able to see the vocabularies or find your way to the items to translate. It seems to be missing links.

**Comment by dashohoxha** [comment]
Basically, https://btranslator.org/ is supposed to be just an API provider (interface to the database) and nothing else. But this is too idealistic, and there are a bunch of things that would be difficult for the clients and can be managed more easily on the server (for example the user accounts and profiles).
More details about the vocabularies, items to be translated etc. are supposed to be found on the clients. https://l10n.org.al is one of the clients (web application), and http://fjalori.fs.al, http://v.btranslator.org are other clients (mobile apps).

However, the server does provide some (web) interface about the items to be translated. What you suggest would be nice to have, but I don't think is a must for the server. Maybe in the future such functionality will be added (by me or if somebody provides any pull request).

**Comment by dashohoxha** [comment]
Mike, this is not exactly what you have requested, but it is a bit related to it.
Now it is possible to see the items of the vocabulary ICT_de on the server, like this:
 - https://btranslator.org/vocabulary/ICT_de

Previously this was possible only from a client, like this:
 - https://l10n.org.al/vocabulary/ICT_de

But I thought that it makes sense to offer it from the server too.
So, I installed on `btr_server` the drupal module `btrVocabulary` (https://github.com/B-Translator/btrclient/tree/7.x-1.x/vocabulary), and then I had to make a small fix to make it work properly on the server (B-Translator/btrclient@33f1f55cece6c573c73f4efcdf1bd6bf67c0249a).

It is also possible to use `?display=iframe` on it, if somebody wants to embed it inside another page, like this: https://btranslator.org/vocabulary/ICT_de?display=iframe
This is an example of it (as described on http://info.btranslator.org/install.html):
```
<div style="width:300px; display:inline-block;
            float:right; border:1px solid #aaa; padding:5px;">
  <h3 style="margin-top:0px; color:#2a2;">Vocabulary: ICT_de</h3>

  <iframe src="https://btranslator.org/vocabulary/ICT_de?display=iframe"
          width="100%" height="350px"
          seamless="seamless" frameborder="0">
  </iframe>
</div>
```

Thanks for your feedback because it is really helping to make things better. In the past even small problems that I could have fixed easily have gone unnoticed for ages, simply because there was no one to try things out.

**Comment by h4ck3rm1k3** [comment]
@dashohoxha when you get to that site somehow, I always end up clicking on the bee, i land on https://btranslator.org/ and it is like a dead end. I just want to be able to get to something to do from there, so it could say : hi , here is something you can do. it seems that it is easy to get lost on the web or in the bee hive, so we should think about new people and how they might get lost and offer them a way to get back to the normal usage.

**Comment by dashohoxha** [comment]
Should we add a "Back" button? ;)
I am joking. You are right.
For the time being the quickest solution would be to redirect to http://info.btranslator.org
Later we can add a list of active translation projects (right now the only active projects are ICT_sq and ICT_de).

**Comment by h4ck3rm1k3** [comment]
yes, http://info.btranslator.org/ is exactly what we want as the main page.

**Comment by dashohoxha** [comment]
I added some links to the active projects and a a link to http://info.btranslator.org/

**Comment by h4ck3rm1k3** [comment]
:+1:
